### ISSUE TITLE
Bot only gets latest 100 messages in each channel

### ISSUE THREAD

**Issue by anodium** [anodium/discord-data-export#2]
Due to this little line (`bot.py`#L40) using `discord.client.logs_from` standalone, it defaults to only fetching 100 messages. We need _every_ message, so maybe iterate over history with the oldest read date in some form of temp variable?

**Comment by hook54321a** [comment]
Has this been fixed yet? Trying to find a way to download all of the chat for some channels. :/

**Comment by anodium** [comment]
@hook54321a I've been having some hardware issues these past few months. I managed to get everything up and running last week, but the holidays have left me with no time to work on code. x_x

I've been taking advantage of the peace and quiet of everyone being hung over from new year's celebrations, so I'll most likely push commits within the next 24 hours. ^_^

**Comment by anodium** [comment]
The whole codebase has been rewritten from the ground up, thus this issue is irrelevant.
